### PR TITLE
updated to asm 6.1 to support Java 9

### PR DESCRIPTION
**Pull request by kontext-e**

### CODE REVIEW

**Comment by obfischer** [comment]
Thank you for your contribution. Could you please also add a note to the release notes about the ability to scan Java 9 byte code?

**Comment by kontext-e** [comment]
Noticed that ASM 6.1 already supports Java 10 and added this to release notes.
Relsolved a conflict in release notes.

**Comment by obfischer** [comment]
Currently the CI build is broken by the latest changes.

**Comment by obfischer** [comment]
@DirkMahler Can you check if there are any uncommited changes? CI is broken currently.

**Comment by DirkMahler** [comment]
Will check this on next Wed (currently on vacations...)

**Comment by kontext-e** [comment]
BTW: which CI build? There is no badge in README and nothing like a .travis file. And it works for me like a charm.

**Pull request merged**
